#!/usr/bin/bash

sudo apt -y update
sudo apt -y install git ripgrep bat eza pavucontrol xclip jq tldr shutter python3-pip

# zoxide
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

# fzf
git clone https://github.com/junegunn/fzf.git $HOME/.local/src/fzf
$HOME/.local/src/fzf/install
